<?php
return array (
  'brand' => 
  array (
    'fieldid' => '199',
    'modelid' => '17',
    'siteid' => '1',
    'field' => 'brand',
    'name' => '品牌车系',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'linkage',
    'setting' => '{"linkageid":"3360","showtype":"1","space":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'linkageid' => '3360',
    'showtype' => '1',
    'space' => '',
  ),
  'pro' => 
  array (
    'fieldid' => '200',
    'modelid' => '17',
    'siteid' => '1',
    'field' => 'pro',
    'name' => '产品名称',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'name' => 
  array (
    'fieldid' => '201',
    'modelid' => '17',
    'siteid' => '1',
    'field' => 'name',
    'name' => '姓名',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'tel' => 
  array (
    'fieldid' => '202',
    'modelid' => '17',
    'siteid' => '1',
    'field' => 'tel',
    'name' => '手机',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '/^(1)[0-9]{10}$/',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'time' => 
  array (
    'fieldid' => '203',
    'modelid' => '17',
    'siteid' => '1',
    'field' => 'time',
    'name' => '预计购车时间',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"\\u4e00\\u4e2a\\u6708\\u5185|1\\r\\n\\u4e09\\u4e2a\\u6708\\u5185|2\\r\\n\\u516d\\u4e2a\\u6708\\u5185|3\\r\\n\\u516d\\u4e2a\\u6708\\u4ee5\\u4e0a|4","boxtype":"radio","fieldtype":"varchar","minnumber":"1","cols":"5","width":"80","size":"1","defaultvalue":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '一个月内|1
三个月内|2
六个月内|3
六个月以上|4',
    'boxtype' => 'radio',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'cols' => '5',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
  ),
  'city' => 
  array (
    'fieldid' => '204',
    'modelid' => '17',
    'siteid' => '1',
    'field' => 'city',
    'name' => '上牌城市',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'linkage',
    'setting' => '{"linkageid":"1","showtype":"1","space":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'linkageid' => '1',
    'showtype' => '1',
    'space' => '',
  ),
  'td' => 
  array (
    'fieldid' => '205',
    'modelid' => '17',
    'siteid' => '1',
    'field' => 'td',
    'name' => '该产品的哪些特点吸引了您',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"\\u53d1\\u52a8\\u673a\\u52a8\\u529b\\u6027\\u80fd|1\\r\\n\\u51fa\\u52e4\\u7387|2\\r\\n\\u5b89\\u5168\\u6027|3\\r\\n\\u64cd\\u63a7\\u6027|4\\r\\n\\u5236\\u52a8\\u6027|5\\r\\n\\u8282\\u6cb9\\u6027|6\\r\\n\\u8212\\u9002\\u6027|7\\r\\n\\u6392\\u653e\\u7cfb\\u7edf\\u6027\\u80fd|8\\r\\n\\u667a\\u80fd\\u6027|9\\r\\n\\u8f7b\\u91cf\\u5316|10\\r\\n\\u914d\\u4ef6\\u4f9b\\u5e94\\u7387|11\\r\\n\\u5185\\u9970\\u505a\\u5de5|12\\r\\n\\u91d1\\u878d\\u652f\\u6301|13\\r\\n\\u4e8c\\u624b\\u8f66\\u6b8b\\u503c|14","boxtype":"checkbox","fieldtype":"varchar","minnumber":"1","cols":"5","width":"80","size":"1","defaultvalue":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '发动机动力性能|1
出勤率|2
安全性|3
操控性|4
制动性|5
节油性|6
舒适性|7
排放系统性能|8
智能性|9
轻量化|10
配件供应率|11
内饰做工|12
金融支持|13
二手车残值|14',
    'boxtype' => 'checkbox',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'cols' => '5',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
  ),
  'other1' => 
  array (
    'fieldid' => '206',
    'modelid' => '17',
    'siteid' => '1',
    'field' => 'other1',
    'name' => '品牌1',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'other2' => 
  array (
    'fieldid' => '207',
    'modelid' => '17',
    'siteid' => '1',
    'field' => 'other2',
    'name' => '品牌2',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'other3' => 
  array (
    'fieldid' => '208',
    'modelid' => '17',
    'siteid' => '1',
    'field' => 'other3',
    'name' => '品牌3',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
);
?>