<?php
return array (
  'title' => '品牌车系',
  'style' => '2',
  'setting' => 
  array (
    'level' => '2',
  ),
  'siteid' => '1',
  'data' => 
  array (
    3361 => 
    array (
      'linkageid' => '3361',
      'name' => '安凯客车',
      'style' => '0',
      'parentid' => '0',
      'child' => 1,
      'arrchildid' => '3361,3364,3365,3632,3633,3634,3635,3636,3637,3638',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'A',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
    ),
    3362 => 
    array (
      'linkageid' => '3362',
      'name' => '比亚迪',
      'style' => '0',
      'parentid' => '0',
      'child' => 1,
      'arrchildid' => '3362,3366,3367',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'B',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
    ),
    3363 => 
    array (
      'linkageid' => '3363',
      'name' => '长安客车',
      'style' => '0',
      'parentid' => '0',
      'child' => 1,
      'arrchildid' => '3363,3368',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'C',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
    ),
    3364 => 
    array (
      'linkageid' => '3364',
      'name' => '安凯宝斯通',
      'style' => '',
      'parentid' => '3361',
      'child' => 0,
      'arrchildid' => '3364',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3365 => 
    array (
      'linkageid' => '3365',
      'name' => '安凯 A8系列',
      'style' => '',
      'parentid' => '3361',
      'child' => 0,
      'arrchildid' => '3365',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3366 => 
    array (
      'linkageid' => '3366',
      'name' => 'Q1',
      'style' => '',
      'parentid' => '3362',
      'child' => 0,
      'arrchildid' => '3366',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3367 => 
    array (
      'linkageid' => '3367',
      'name' => '比亚迪C系',
      'style' => '',
      'parentid' => '3362',
      'child' => 0,
      'arrchildid' => '3367',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3368 => 
    array (
      'linkageid' => '3368',
      'name' => '长安公交客车',
      'style' => '',
      'parentid' => '3363',
      'child' => 0,
      'arrchildid' => '3368',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3369 => 
    array (
      'linkageid' => '3369',
      'name' => '安徽开乐',
      'style' => '0',
      'parentid' => '0',
      'child' => 1,
      'arrchildid' => '3369,3625,3626,3627,3628,3639,3640,3641',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'A',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
    ),
    3370 => 
    array (
      'linkageid' => '3370',
      'name' => '艾里逊',
      'style' => '',
      'parentid' => '0',
      'child' => 1,
      'arrchildid' => '3370,3629,3630,3631,3642,3643,3644',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'A',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3371 => 
    array (
      'linkageid' => '3371',
      'name' => 'BPW梅州车桥',
      'style' => '',
      'parentid' => '0',
      'child' => 1,
      'arrchildid' => '3371,3645',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'B',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3372 => 
    array (
      'linkageid' => '3372',
      'name' => '北奔重卡',
      'style' => '',
      'parentid' => '0',
      'child' => 1,
      'arrchildid' => '3372,3646,3647,3648,3649,3650,3651,3652,3653',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'B',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3373 => 
    array (
      'linkageid' => '3373',
      'name' => '北京牌',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3373',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'B',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3374 => 
    array (
      'linkageid' => '3374',
      'name' => '倍耐力',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3374',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'B',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3375 => 
    array (
      'linkageid' => '3375',
      'name' => '奔驰卡车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3375',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'B',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3376 => 
    array (
      'linkageid' => '3376',
      'name' => '宝石',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3376',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'B',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3377 => 
    array (
      'linkageid' => '3377',
      'name' => '博世',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3377',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'B',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3378 => 
    array (
      'linkageid' => '3378',
      'name' => '北汽银翔',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3378',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'B',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3379 => 
    array (
      'linkageid' => '3379',
      'name' => '北汽制造',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3379',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'B',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3380 => 
    array (
      'linkageid' => '3380',
      'name' => '采埃孚',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3380',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'C',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3381 => 
    array (
      'linkageid' => '3381',
      'name' => '长城汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3381',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'C',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3382 => 
    array (
      'linkageid' => '3382',
      'name' => '长城润滑油',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3382',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'C',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3383 => 
    array (
      'linkageid' => '3383',
      'name' => '长安轻型商用车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3383',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'C',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3384 => 
    array (
      'linkageid' => '3384',
      'name' => '昌河',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3384',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'C',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3385 => 
    array (
      'linkageid' => '3385',
      'name' => '常隆客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3385',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'C',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3386 => 
    array (
      'linkageid' => '3386',
      'name' => '朝柴',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3386',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'C',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3387 => 
    array (
      'linkageid' => '3387',
      'name' => '成功汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3387',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'C',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3388 => 
    array (
      'linkageid' => '3388',
      'name' => '成山轮胎',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3388',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'C',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3389 => 
    array (
      'linkageid' => '3389',
      'name' => '常熟申毅',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3389',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'C',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3390 => 
    array (
      'linkageid' => '3390',
      'name' => '重庆康明斯',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3390',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'C',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3391 => 
    array (
      'linkageid' => '3391',
      'name' => '常柴',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3391',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'C',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3392 => 
    array (
      'linkageid' => '3392',
      'name' => '大柴',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3392',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3393 => 
    array (
      'linkageid' => '3393',
      'name' => '大齿变速箱',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3393',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3394 => 
    array (
      'linkageid' => '3394',
      'name' => '达夫',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3394',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3395 => 
    array (
      'linkageid' => '3395',
      'name' => '大运汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3395',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3396 => 
    array (
      'linkageid' => '3396',
      'name' => '大众进口车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3396',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3397 => 
    array (
      'linkageid' => '3397',
      'name' => '戴卡宏鑫',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3397',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3398 => 
    array (
      'linkageid' => '3398',
      'name' => '道达尔',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3398',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3399 => 
    array (
      'linkageid' => '3399',
      'name' => '德纳',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3399',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3400 => 
    array (
      'linkageid' => '3400',
      'name' => '东风超龙客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3400',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3401 => 
    array (
      'linkageid' => '3401',
      'name' => '东风柳汽',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3401',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3402 => 
    array (
      'linkageid' => '3402',
      'name' => '东风股份',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3402',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3403 => 
    array (
      'linkageid' => '3403',
      'name' => '东风康明斯',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3403',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3404 => 
    array (
      'linkageid' => '3404',
      'name' => '东风商用车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3404',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3405 => 
    array (
      'linkageid' => '3405',
      'name' => '东风小康',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3405',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3406 => 
    array (
      'linkageid' => '3406',
      'name' => '东风御风',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3406',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3407 => 
    array (
      'linkageid' => '3407',
      'name' => '东风神宇',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3407',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3408 => 
    array (
      'linkageid' => '3408',
      'name' => '东沃',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3408',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3409 => 
    array (
      'linkageid' => '3409',
      'name' => '邓禄普',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3409',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3410 => 
    array (
      'linkageid' => '3410',
      'name' => '道奇',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3410',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3411 => 
    array (
      'linkageid' => '3411',
      'name' => '东南汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3411',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3412 => 
    array (
      'linkageid' => '3412',
      'name' => '东风南充',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3412',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'D',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3413 => 
    array (
      'linkageid' => '3413',
      'name' => '福建侨龙',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3413',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3414 => 
    array (
      'linkageid' => '3414',
      'name' => '福伊特',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3414',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3415 => 
    array (
      'linkageid' => '3415',
      'name' => '法士特',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3415',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3416 => 
    array (
      'linkageid' => '3416',
      'name' => '风神轮胎',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3416',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3417 => 
    array (
      'linkageid' => '3417',
      'name' => '富华车桥',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3417',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3418 => 
    array (
      'linkageid' => '3418',
      'name' => '弗列加',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3418',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3419 => 
    array (
      'linkageid' => '3419',
      'name' => '福建奔驰',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3419',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3420 => 
    array (
      'linkageid' => '3420',
      'name' => '福特汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3420',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3421 => 
    array (
      'linkageid' => '3421',
      'name' => '丰田汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3421',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3422 => 
    array (
      'linkageid' => '3422',
      'name' => '福田奥铃',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3422',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3423 => 
    array (
      'linkageid' => '3423',
      'name' => '福田戴姆勒',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3423',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3424 => 
    array (
      'linkageid' => '3424',
      'name' => '福田风景',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3424',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3425 => 
    array (
      'linkageid' => '3425',
      'name' => '福田伽途',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3425',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3426 => 
    array (
      'linkageid' => '3426',
      'name' => '福田康明斯',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3426',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3427 => 
    array (
      'linkageid' => '3427',
      'name' => '福田雷沃',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3427',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3428 => 
    array (
      'linkageid' => '3428',
      'name' => '福田蒙派克',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3428',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3429 => 
    array (
      'linkageid' => '3429',
      'name' => '福田商务车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3429',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3430 => 
    array (
      'linkageid' => '3430',
      'name' => '福田拓路者',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3430',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3431 => 
    array (
      'linkageid' => '3431',
      'name' => '福田欧辉客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3431',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3432 => 
    array (
      'linkageid' => '3432',
      'name' => '福田欧马可',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3432',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3433 => 
    array (
      'linkageid' => '3433',
      'name' => '福田瑞沃',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3433',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3434 => 
    array (
      'linkageid' => '3434',
      'name' => '福田萨普',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3434',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3435 => 
    array (
      'linkageid' => '3435',
      'name' => '福斯',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3435',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3436 => 
    array (
      'linkageid' => '3436',
      'name' => '福田时代汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3436',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3437 => 
    array (
      'linkageid' => '3437',
      'name' => '富成星驰',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3437',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3438 => 
    array (
      'linkageid' => '3438',
      'name' => '法斯特',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3438',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3439 => 
    array (
      'linkageid' => '3439',
      'name' => '福田环保动力',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3439',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3440 => 
    array (
      'linkageid' => '3440',
      'name' => '福迪皮卡',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3440',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'F',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3441 => 
    array (
      'linkageid' => '3441',
      'name' => '固铂',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3441',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'G',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3442 => 
    array (
      'linkageid' => '3442',
      'name' => '固特异',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3442',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'G',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3443 => 
    array (
      'linkageid' => '3443',
      'name' => '广汽日野',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3443',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'G',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3444 => 
    array (
      'linkageid' => '3444',
      'name' => '贵州轮胎',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3444',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'G',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3445 => 
    array (
      'linkageid' => '3445',
      'name' => '广汽吉奥',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3445',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'G',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3446 => 
    array (
      'linkageid' => '3446',
      'name' => '华劲',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3446',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3447 => 
    array (
      'linkageid' => '3447',
      'name' => '华神',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3447',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3448 => 
    array (
      'linkageid' => '3448',
      'name' => '湖北三环',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3448',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3449 => 
    array (
      'linkageid' => '3449',
      'name' => '瀚瑞森',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3449',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3450 => 
    array (
      'linkageid' => '3450',
      'name' => '海沃',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3450',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3451 => 
    array (
      'linkageid' => '3451',
      'name' => '哈齿变速箱',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3451',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3452 => 
    array (
      'linkageid' => '3452',
      'name' => '海马汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3452',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3453 => 
    array (
      'linkageid' => '3453',
      'name' => '海格汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3453',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3454 => 
    array (
      'linkageid' => '3454',
      'name' => '海格客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3454',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3455 => 
    array (
      'linkageid' => '3455',
      'name' => '韩泰',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3455',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3456 => 
    array (
      'linkageid' => '3456',
      'name' => '汉德',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3456',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3457 => 
    array (
      'linkageid' => '3457',
      'name' => '汉马动力',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3457',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3458 => 
    array (
      'linkageid' => '3458',
      'name' => '横滨',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3458',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3459 => 
    array (
      'linkageid' => '3459',
      'name' => '华晨金杯',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3459',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3460 => 
    array (
      'linkageid' => '3460',
      'name' => '华菱星马',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3460',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3461 => 
    array (
      'linkageid' => '3461',
      'name' => '黄海汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3461',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3462 => 
    array (
      'linkageid' => '3462',
      'name' => '哈弗',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3462',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3463 => 
    array (
      'linkageid' => '3463',
      'name' => '华源莱动',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3463',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3464 => 
    array (
      'linkageid' => '3464',
      'name' => '恒天新能源汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3464',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'H',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3465 => 
    array (
      'linkageid' => '3465',
      'name' => '江铃全顺',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3465',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3466 => 
    array (
      'linkageid' => '3466',
      'name' => '江淮瑞风',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3466',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3467 => 
    array (
      'linkageid' => '3467',
      'name' => '江淮格尔发',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3467',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3468 => 
    array (
      'linkageid' => '3468',
      'name' => '江淮客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3468',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3469 => 
    array (
      'linkageid' => '3469',
      'name' => '江淮星锐',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3469',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3470 => 
    array (
      'linkageid' => '3470',
      'name' => '江淮帅铃',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3470',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3471 => 
    array (
      'linkageid' => '3471',
      'name' => '江淮康铃',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3471',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3472 => 
    array (
      'linkageid' => '3472',
      'name' => '江淮骏铃',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3472',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3473 => 
    array (
      'linkageid' => '3473',
      'name' => '金旅客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3473',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3474 => 
    array (
      'linkageid' => '3474',
      'name' => '金龙客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3474',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3475 => 
    array (
      'linkageid' => '3475',
      'name' => '嘉世通',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3475',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3476 => 
    array (
      'linkageid' => '3476',
      'name' => '锦湖轮胎',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3476',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3477 => 
    array (
      'linkageid' => '3477',
      'name' => '金东',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3477',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3478 => 
    array (
      'linkageid' => '3478',
      'name' => '江铃汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3478',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3479 => 
    array (
      'linkageid' => '3479',
      'name' => '江铃皮卡',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3479',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3480 => 
    array (
      'linkageid' => '3480',
      'name' => '吉利商用车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3480',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3481 => 
    array (
      'linkageid' => '3481',
      'name' => '九龙汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3481',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3482 => 
    array (
      'linkageid' => '3482',
      'name' => '佳通轮胎',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3482',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3483 => 
    array (
      'linkageid' => '3483',
      'name' => '江淮锐捷特',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3483',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3484 => 
    array (
      'linkageid' => '3484',
      'name' => '江西五十铃',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3484',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3485 => 
    array (
      'linkageid' => '3485',
      'name' => '江铃轻汽',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3485',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3486 => 
    array (
      'linkageid' => '3486',
      'name' => '嘉实多',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3486',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3487 => 
    array (
      'linkageid' => '3487',
      'name' => '江淮纳威司达',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3487',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3488 => 
    array (
      'linkageid' => '3488',
      'name' => '江铃重卡',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3488',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3489 => 
    array (
      'linkageid' => '3489',
      'name' => '江铃轻卡',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3489',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'J',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3490 => 
    array (
      'linkageid' => '3490',
      'name' => '康迪泰克',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3490',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'K',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3491 => 
    array (
      'linkageid' => '3491',
      'name' => '康迈',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3491',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'K',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3492 => 
    array (
      'linkageid' => '3492',
      'name' => '凯卓立',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3492',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'K',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3493 => 
    array (
      'linkageid' => '3493',
      'name' => '卡威',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3493',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'K',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3494 => 
    array (
      'linkageid' => '3494',
      'name' => '凯马',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3494',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'K',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3495 => 
    array (
      'linkageid' => '3495',
      'name' => '康明斯',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3495',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'K',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3496 => 
    array (
      'linkageid' => '3496',
      'name' => '卡特彼勒',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3496',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'K',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3497 => 
    array (
      'linkageid' => '3497',
      'name' => '开瑞绿卡',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3497',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'K',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3498 => 
    array (
      'linkageid' => '3498',
      'name' => '昆仑润滑油',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3498',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'K',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3499 => 
    array (
      'linkageid' => '3499',
      'name' => '可兰素',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3499',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'K',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3500 => 
    array (
      'linkageid' => '3500',
      'name' => '康普顿',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3500',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'K',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3501 => 
    array (
      'linkageid' => '3501',
      'name' => '克诺尔',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3501',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'K',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3502 => 
    array (
      'linkageid' => '3502',
      'name' => '雷萨重机',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3502',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'L',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3503 => 
    array (
      'linkageid' => '3503',
      'name' => '雷诺',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3503',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'L',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3504 => 
    array (
      'linkageid' => '3504',
      'name' => '玲珑轮胎',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3504',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'L',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3505 => 
    array (
      'linkageid' => '3505',
      'name' => '力帆时骏',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3505',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'L',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3506 => 
    array (
      'linkageid' => '3506',
      'name' => '力帆骏马',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3506',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'L',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3507 => 
    array (
      'linkageid' => '3507',
      'name' => '联合卡车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3507',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'L',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3508 => 
    array (
      'linkageid' => '3508',
      'name' => '龙蟠润滑油',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3508',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'L',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3509 => 
    array (
      'linkageid' => '3509',
      'name' => '浪马轮胎',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3509',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'L',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3510 => 
    array (
      'linkageid' => '3510',
      'name' => '雷沃动力',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3510',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'L',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3511 => 
    array (
      'linkageid' => '3511',
      'name' => '曼',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3511',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'M',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3512 => 
    array (
      'linkageid' => '3512',
      'name' => '米其林',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3512',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'M',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3513 => 
    array (
      'linkageid' => '3513',
      'name' => '美孚黑霸王',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3513',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'M',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3514 => 
    array (
      'linkageid' => '3514',
      'name' => '美铝',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3514',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'M',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3515 => 
    array (
      'linkageid' => '3515',
      'name' => '美驰车桥',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3515',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'M',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3516 => 
    array (
      'linkageid' => '3516',
      'name' => '美丰加蓝',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3516',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'M',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3517 => 
    array (
      'linkageid' => '3517',
      'name' => '美国通用',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3517',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'M',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3518 => 
    array (
      'linkageid' => '3518',
      'name' => '南京金龙',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3518',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'N',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3519 => 
    array (
      'linkageid' => '3519',
      'name' => '南骏汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3519',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'N',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3520 => 
    array (
      'linkageid' => '3520',
      'name' => '南京依维柯',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3520',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'N',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3521 => 
    array (
      'linkageid' => '3521',
      'name' => '南昌江铃',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3521',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'N',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3522 => 
    array (
      'linkageid' => '3522',
      'name' => '欧舒特客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3522',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'O',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3523 => 
    array (
      'linkageid' => '3523',
      'name' => '普利司通',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3523',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'P',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3524 => 
    array (
      'linkageid' => '3524',
      'name' => '派克',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3524',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'P',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3525 => 
    array (
      'linkageid' => '3525',
      'name' => '佩卡',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3525',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'P',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3526 => 
    array (
      'linkageid' => '3526',
      'name' => '全柴',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3526',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Q',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3527 => 
    array (
      'linkageid' => '3527',
      'name' => '綦齿',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3527',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Q',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3528 => 
    array (
      'linkageid' => '3528',
      'name' => '壳牌',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3528',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Q',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3529 => 
    array (
      'linkageid' => '3529',
      'name' => '壳牌统一',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3529',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Q',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3530 => 
    array (
      'linkageid' => '3530',
      'name' => '奇瑞重工',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3530',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Q',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3531 => 
    array (
      'linkageid' => '3531',
      'name' => '青年客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3531',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Q',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3532 => 
    array (
      'linkageid' => '3532',
      'name' => '庆铃',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3532',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Q',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3533 => 
    array (
      'linkageid' => '3533',
      'name' => '山东锣响',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3533',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3534 => 
    array (
      'linkageid' => '3534',
      'name' => '水泊焊割',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3534',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3535 => 
    array (
      'linkageid' => '3535',
      'name' => '山西同元',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3535',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3536 => 
    array (
      'linkageid' => '3536',
      'name' => '上饶客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3536',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3537 => 
    array (
      'linkageid' => '3537',
      'name' => '舒驰客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3537',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3538 => 
    array (
      'linkageid' => '3538',
      'name' => '三角轮胎',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3538',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3539 => 
    array (
      'linkageid' => '3539',
      'name' => '三环十通',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3539',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3540 => 
    array (
      'linkageid' => '3540',
      'name' => '三一重工',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3540',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3541 => 
    array (
      'linkageid' => '3541',
      'name' => '斯太尔动力',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3541',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3542 => 
    array (
      'linkageid' => '3542',
      'name' => '斯堪尼亚',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3542',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3543 => 
    array (
      'linkageid' => '3543',
      'name' => '四川现代',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3543',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3544 => 
    array (
      'linkageid' => '3544',
      'name' => '陕汽重卡',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3544',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3545 => 
    array (
      'linkageid' => '3545',
      'name' => '少林客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3545',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3546 => 
    array (
      'linkageid' => '3546',
      'name' => '申龙客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3546',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3547 => 
    array (
      'linkageid' => '3547',
      'name' => '申沃客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3547',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3548 => 
    array (
      'linkageid' => '3548',
      'name' => '上汽红岩',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3548',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3549 => 
    array (
      'linkageid' => '3549',
      'name' => '上汽菲亚特红岩',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3549',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3550 => 
    array (
      'linkageid' => '3550',
      'name' => '上汽通用五菱',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3550',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3551 => 
    array (
      'linkageid' => '3551',
      'name' => '上汽大通',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3551',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3552 => 
    array (
      'linkageid' => '3552',
      'name' => '上海日野',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3552',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3553 => 
    array (
      'linkageid' => '3553',
      'name' => '上汽跃进',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3553',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3554 => 
    array (
      'linkageid' => '3554',
      'name' => '双特',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3554',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3555 => 
    array (
      'linkageid' => '3555',
      'name' => '双星轮胎',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3555',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3556 => 
    array (
      'linkageid' => '3556',
      'name' => '双喜轮胎',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3556',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3557 => 
    array (
      'linkageid' => '3557',
      'name' => '双钱轮胎',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3557',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3558 => 
    array (
      'linkageid' => '3558',
      'name' => '上柴',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3558',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3559 => 
    array (
      'linkageid' => '3559',
      'name' => '四达动力',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3559',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3560 => 
    array (
      'linkageid' => '3560',
      'name' => '山东银宝',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3560',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'S',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3561 => 
    array (
      'linkageid' => '3561',
      'name' => '泰乐玛',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3561',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'T',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3562 => 
    array (
      'linkageid' => '3562',
      'name' => '通伊欧轮胎',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3562',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'T',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3563 => 
    array (
      'linkageid' => '3563',
      'name' => '太仓京和机电',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3563',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'T',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3564 => 
    array (
      'linkageid' => '3564',
      'name' => '潍柴',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3564',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'W',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3565 => 
    array (
      'linkageid' => '3565',
      'name' => '威尔耐',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3565',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'W',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3566 => 
    array (
      'linkageid' => '3566',
      'name' => '威伯科',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3566',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'W',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3567 => 
    array (
      'linkageid' => '3567',
      'name' => '五十铃',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3567',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'W',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3568 => 
    array (
      'linkageid' => '3568',
      'name' => '五征汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3568',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'W',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3569 => 
    array (
      'linkageid' => '3569',
      'name' => '五洲龙客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3569',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'W',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3570 => 
    array (
      'linkageid' => '3570',
      'name' => '沃尔沃',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3570',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'W',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3571 => 
    array (
      'linkageid' => '3571',
      'name' => '韦博思通',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3571',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'W',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3572 => 
    array (
      'linkageid' => '3572',
      'name' => '五菱柳机',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3572',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'W',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3573 => 
    array (
      'linkageid' => '3573',
      'name' => '万里扬变速器',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3573',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'W',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3574 => 
    array (
      'linkageid' => '3574',
      'name' => '微宏动力',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3574',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'W',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3575 => 
    array (
      'linkageid' => '3575',
      'name' => '新沃运力',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3575',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'X',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3576 => 
    array (
      'linkageid' => '3576',
      'name' => '新飞',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3576',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'X',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3577 => 
    array (
      'linkageid' => '3577',
      'name' => '新宏昌',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3577',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'X',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3578 => 
    array (
      'linkageid' => '3578',
      'name' => '西沃客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3578',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'X',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3579 => 
    array (
      'linkageid' => '3579',
      'name' => '新柴',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3579',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'X',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3580 => 
    array (
      'linkageid' => '3580',
      'name' => '雪佛兰',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3580',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'X',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3581 => 
    array (
      'linkageid' => '3581',
      'name' => '徐工重卡',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3581',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'X',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3582 => 
    array (
      'linkageid' => '3582',
      'name' => '中泰兴龙',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3582',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3583 => 
    array (
      'linkageid' => '3583',
      'name' => '新晨动力',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3583',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'X',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3584 => 
    array (
      'linkageid' => '3584',
      'name' => '西安康明斯',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3584',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'X',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3585 => 
    array (
      'linkageid' => '3585',
      'name' => '玉柴联合动力',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3585',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3586 => 
    array (
      'linkageid' => '3586',
      'name' => '永强汽车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3586',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3587 => 
    array (
      'linkageid' => '3587',
      'name' => '约斯特',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3587',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3588 => 
    array (
      'linkageid' => '3588',
      'name' => '扬子江客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3588',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3589 => 
    array (
      'linkageid' => '3589',
      'name' => '亚星客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3589',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3590 => 
    array (
      'linkageid' => '3590',
      'name' => '沂星客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3590',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3591 => 
    array (
      'linkageid' => '3591',
      'name' => '银隆客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3591',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3592 => 
    array (
      'linkageid' => '3592',
      'name' => '依维柯',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3592',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3593 => 
    array (
      'linkageid' => '3593',
      'name' => '义和车桥',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3593',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3594 => 
    array (
      'linkageid' => '3594',
      'name' => '伊顿',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3594',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3595 => 
    array (
      'linkageid' => '3595',
      'name' => '宇通客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3595',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3596 => 
    array (
      'linkageid' => '3596',
      'name' => '玉柴',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3596',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3597 => 
    array (
      'linkageid' => '3597',
      'name' => '云内动力',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3597',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3598 => 
    array (
      'linkageid' => '3598',
      'name' => '扬柴',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3598',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3599 => 
    array (
      'linkageid' => '3599',
      'name' => '一汽解放',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3599',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3600 => 
    array (
      'linkageid' => '3600',
      'name' => '一汽解放青岛',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3600',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3601 => 
    array (
      'linkageid' => '3601',
      'name' => '一汽客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3601',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3602 => 
    array (
      'linkageid' => '3602',
      'name' => '一汽柳特',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3602',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3603 => 
    array (
      'linkageid' => '3603',
      'name' => '一汽通用',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3603',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3604 => 
    array (
      'linkageid' => '3604',
      'name' => '一汽凌源',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3604',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3605 => 
    array (
      'linkageid' => '3605',
      'name' => '溢通',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3605',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3606 => 
    array (
      'linkageid' => '3606',
      'name' => '雅固车轮',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3606',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3607 => 
    array (
      'linkageid' => '3607',
      'name' => '雅士',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3607',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3608 => 
    array (
      'linkageid' => '3608',
      'name' => '一汽四环',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3608',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3609 => 
    array (
      'linkageid' => '3609',
      'name' => '一汽坤程皮卡',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3609',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3610 => 
    array (
      'linkageid' => '3610',
      'name' => '一汽锡柴',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3610',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Y',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3611 => 
    array (
      'linkageid' => '3611',
      'name' => '中国重汽海西',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3611',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3612 => 
    array (
      'linkageid' => '3612',
      'name' => '中国重汽商销',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3612',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3613 => 
    array (
      'linkageid' => '3613',
      'name' => '中兴皮卡',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3613',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3614 => 
    array (
      'linkageid' => '3614',
      'name' => '正新轮胎',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3614',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3615 => 
    array (
      'linkageid' => '3615',
      'name' => '住友',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3615',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3616 => 
    array (
      'linkageid' => '3616',
      'name' => '中国重汽发动机',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3616',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3617 => 
    array (
      'linkageid' => '3617',
      'name' => '正泰希尔',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3617',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3618 => 
    array (
      'linkageid' => '3618',
      'name' => '中集车辆集团',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3618',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3619 => 
    array (
      'linkageid' => '3619',
      'name' => '中联桥',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3619',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3620 => 
    array (
      'linkageid' => '3620',
      'name' => '中通客车',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3620',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3621 => 
    array (
      'linkageid' => '3621',
      'name' => '中国重汽销司',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3621',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3622 => 
    array (
      'linkageid' => '3622',
      'name' => '中国重汽王牌',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3622',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3623 => 
    array (
      'linkageid' => '3623',
      'name' => '中国重汽轻卡',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3623',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3624 => 
    array (
      'linkageid' => '3624',
      'name' => '郑州日产',
      'style' => '',
      'parentid' => '0',
      'child' => 0,
      'arrchildid' => '3624',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'Z',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3625 => 
    array (
      'linkageid' => '3625',
      'name' => '普通栏板半挂车',
      'style' => '0',
      'parentid' => '3369',
      'child' => 0,
      'arrchildid' => '3625',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
    ),
    3626 => 
    array (
      'linkageid' => '3626',
      'name' => 'AKL5160GYYDFL01',
      'style' => '0',
      'parentid' => '3369',
      'child' => 0,
      'arrchildid' => '3626',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
    ),
    3627 => 
    array (
      'linkageid' => '3627',
      'name' => 'AKL5160XLCHFC02',
      'style' => '0',
      'parentid' => '3369',
      'child' => 0,
      'arrchildid' => '3627',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
    ),
    3628 => 
    array (
      'linkageid' => '3628',
      'name' => 'AKL5040XLCHFC01',
      'style' => '',
      'parentid' => '3369',
      'child' => 0,
      'arrchildid' => '3628',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3629 => 
    array (
      'linkageid' => '3629',
      'name' => '9000系列',
      'style' => '0',
      'parentid' => '3370',
      'child' => 0,
      'arrchildid' => '3629',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
    ),
    3630 => 
    array (
      'linkageid' => '3630',
      'name' => '6000系列',
      'style' => '0',
      'parentid' => '3370',
      'child' => 0,
      'arrchildid' => '3630',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
    ),
    3631 => 
    array (
      'linkageid' => '3631',
      'name' => '3000/4000系列',
      'style' => '0',
      'parentid' => '3370',
      'child' => 0,
      'arrchildid' => '3631',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
    ),
    3632 => 
    array (
      'linkageid' => '3632',
      'name' => 'K07D系列',
      'style' => '',
      'parentid' => '3361',
      'child' => 0,
      'arrchildid' => '3632',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3633 => 
    array (
      'linkageid' => '3633',
      'name' => 'K40D系列',
      'style' => '',
      'parentid' => '3361',
      'child' => 0,
      'arrchildid' => '3633',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3634 => 
    array (
      'linkageid' => '3634',
      'name' => 'K06D系列',
      'style' => '',
      'parentid' => '3361',
      'child' => 0,
      'arrchildid' => '3634',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3635 => 
    array (
      'linkageid' => '3635',
      'name' => 'LK10D系列',
      'style' => '',
      'parentid' => '3361',
      'child' => 0,
      'arrchildid' => '3635',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3636 => 
    array (
      'linkageid' => '3636',
      'name' => 'A6系列',
      'style' => '',
      'parentid' => '3361',
      'child' => 0,
      'arrchildid' => '3636',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3637 => 
    array (
      'linkageid' => '3637',
      'name' => 'GT系列',
      'style' => '',
      'parentid' => '3361',
      'child' => 0,
      'arrchildid' => '3637',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3638 => 
    array (
      'linkageid' => '3638',
      'name' => '星巴系列',
      'style' => '',
      'parentid' => '3361',
      'child' => 0,
      'arrchildid' => '3638',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3639 => 
    array (
      'linkageid' => '3639',
      'name' => 'AKL5310GRYBJ01',
      'style' => '',
      'parentid' => '3369',
      'child' => 0,
      'arrchildid' => '3639',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3640 => 
    array (
      'linkageid' => '3640',
      'name' => 'AKL5310GRYBJ01',
      'style' => '',
      'parentid' => '3369',
      'child' => 0,
      'arrchildid' => '3640',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3641 => 
    array (
      'linkageid' => '3641',
      'name' => 'AKL5040XLCDFA',
      'style' => '',
      'parentid' => '3369',
      'child' => 0,
      'arrchildid' => '3641',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3642 => 
    array (
      'linkageid' => '3642',
      'name' => '8000系列',
      'style' => '',
      'parentid' => '3370',
      'child' => 0,
      'arrchildid' => '3642',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3643 => 
    array (
      'linkageid' => '3643',
      'name' => '5000系列',
      'style' => '',
      'parentid' => '3370',
      'child' => 0,
      'arrchildid' => '3643',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3644 => 
    array (
      'linkageid' => '3644',
      'name' => '1000/2000系列',
      'style' => '',
      'parentid' => '3370',
      'child' => 0,
      'arrchildid' => '3644',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3645 => 
    array (
      'linkageid' => '3645',
      'name' => '挂车桥',
      'style' => '',
      'parentid' => '3371',
      'child' => 0,
      'arrchildid' => '3645',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3646 => 
    array (
      'linkageid' => '3646',
      'name' => '转向桥',
      'style' => '',
      'parentid' => '3372',
      'child' => 0,
      'arrchildid' => '3646',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3647 => 
    array (
      'linkageid' => '3647',
      'name' => '驱动桥',
      'style' => '',
      'parentid' => '3372',
      'child' => 0,
      'arrchildid' => '3647',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3648 => 
    array (
      'linkageid' => '3648',
      'name' => 'NG80',
      'style' => '',
      'parentid' => '3372',
      'child' => 0,
      'arrchildid' => '3648',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3649 => 
    array (
      'linkageid' => '3649',
      'name' => '北奔V3',
      'style' => '',
      'parentid' => '3372',
      'child' => 0,
      'arrchildid' => '3649',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3650 => 
    array (
      'linkageid' => '3650',
      'name' => '北奔重卡',
      'style' => '',
      'parentid' => '3372',
      'child' => 0,
      'arrchildid' => '3650',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3651 => 
    array (
      'linkageid' => '3651',
      'name' => '北驰系列',
      'style' => '',
      'parentid' => '3372',
      'child' => 0,
      'arrchildid' => '3651',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3652 => 
    array (
      'linkageid' => '3652',
      'name' => '北奔V3M',
      'style' => '',
      'parentid' => '3372',
      'child' => 0,
      'arrchildid' => '3652',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3653 => 
    array (
      'linkageid' => '3653',
      'name' => '北奔V3HT',
      'style' => '',
      'parentid' => '3372',
      'child' => 0,
      'arrchildid' => '3653',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>